apiVersion: v1
kind: Pod
metadata: 
    name: fresco-nginx-Pod
spec:
  containers:
    - name: fresco-nginx-container
      image: nginx
      env:
        - name: SERVER_URL_ENV
          valueFrom:
              ConfigMapKeyRef:
                  name: fresco-config
                  key: SERVER_URL
      volumeMounts:
          - name: fresco-secret
            mountPath: /etc/test
          - name: pvc-volume
            mountPath: /usr/share/nginx/html
  volumes:
    - name: fresco-secret
      secret:
        secretName: fresco-secret
    - name: pvc-volume
      PersistentVolumeClaim:
         claimName: fresco-pvc  