apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
   name: emp-bind 
   namespace: dev
subjects:
  - kind: User
    name: emp
    apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    name: emp-role
    apiGroup: rbac.authorization.k8s.io

---
#clusterrole binding

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readonly-clusterrolebinding
subjects:
  - kind: User  # Can also be ServiceAccount or Group depending on your use case
    name: your-username  # Replace with the actual user or service account name
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: read-only-clusterrole
  apiGroup: rbac.authorization.k8s.io